### ISSUE TITLE
Make tighter tooltip display

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#103]
It's kind of annoying that at least on laptop if you expand heatmap plots and hover over site the tooltip is so large you can't see the most important things like site number and mutation. Is there a way we can make it smaller (perhaps by having less empty space between lines) or point down from cursor as I think it displays up from cursor now and there just isn't enough space for it. @WillHannon-MCB 
<img width="1440" alt="Screenshot 2024-05-17 at 9 44 22 AM" src="https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/29eb08a1-e7a0-4244-8e5c-ea492d72c9d3">

**Comment by jbloom** [comment]
If it is not possible to shrink how tooltip is displayed (which would obviously be best solution if @WillHannon-MCB knows how), we could also just reduce number of things shown in tooltips.

**Comment by WillHannon-MCB** [comment]
I'll make the tooltip smaller and shrink the line spacing.

**Comment by WillHannon-MCB** [comment]
To quickly shrink the space between lines in the `Altair` plot, add `line-height: 0%;` under [this line](https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/blob/b241242df5d5b532bfa71340b00e9e42dde0982b/homepage/.vitepress/theme/Altair.vue#L111). The updated CSS should look like this:

```
.vega-chart-container {
    width: 100%;
    height: auto;
    overflow: auto;
    padding: 20px;
    position: relative;
    background-color: white;
    line-height: 0%;
}
```
It'll be quickest to update only this repo. I'm working on general style changes to the `Altair` component in the `dms-vep-pipeline-3` repo, but I'm not finished.

**Comment by jbloom** [comment]
Great, thanks. @Bernadetadad, do you think it is important to do this now, or can we just wait for the more general fixes?

**Comment by Bernadetadad** [comment]
for now we can just wait as there are ways around this. Let's just do this before we post the pre-print.
