### ISSUE TITLE
make footer a hyperlink?

### ISSUE THREAD

**Issue by jbloom** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#115]
@WillHannon-MCB, how do I make the footer defined in `.vitepress/config.mjs` a hyperlink, so it can link to the citation? Just putting a Markdown link did not work.

**Comment by WillHannon-MCB** [comment]
You can add links to the footer using `HTML`:

```js
footer: {
      message: '<a href="https://www.biorxiv.org/content/10.1101/2024.05.23.595634v1">Study</a> by Bernadeta Dadonaite, Jesse Bloom, et al.',
    },
```
