### ISSUE TITLE
Antibody summary display

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#136]
The current [faceted summary view](https://dms-vep.org/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/htmls/VRC_antibody_escape_faceted.html) of antibodies from VRC has a couple issues:
- I don't think it should have mean antibody escape for all antibodies at the top, I'm not sure that gives any useful information 
- There needs to be more spacing between the facets because antibody names do not fit (or maybe antibody names should be displayed vertically)
- I did include `no_heatmap: True` setting for the antibodies because I think the sliders are sufficient in this case and heatmaps just clutter things but for some reason heatmaps are still being displayed (probably overwritten by `phenotypes` params), I'm not sure how to fix this

**Comment by jbloom** [comment]
@Bernadetadad Are you sure you get heatmaps if you put `no_heatmap` both for the antibodies and each phenotype? When I do that I don't see any heatmaps. Note you need to put `no_heatmap: true` under each antibody set, not as a top-level key for `antibody_escape`.

I am working on the other things still.
