### ISSUE TITLE
slider fonts in `altair` embedded plots w VitePress

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#80]
@jbloom On documentation pages something strange is going on with the way sliders are being displayed
<img width="773" alt="image" src="https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/9e1a1bd4-5b19-44b1-8885-b16e6a2984ec">

**Comment by WillHannon-MCB** [comment]
It's probably an issue with the fonts. My guess is that the fonts aren't being loaded as they should an there isn't a backup specified. I'll dig a bit deeper and fix the issue.

**Comment by Bernadetadad** [comment]
I'm going to close this, It seems to have resolved itself.
