### ISSUE TITLE
mature H5 site numbering is incorrect

### ISSUE THREAD

**Issue by jbloom** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#84]
@Bernadetadad, I think you have the *mature_H5_site* numbering incorrect, in that it should start with -16 and then go down to -1, rather than start with -1 and then go to -16. Can you confirm this is wrong? If so, reply here and I can fix.

**Comment by Bernadetadad** [comment]
yes, you are correct

**Comment by jbloom** [comment]
I'm actually expanding this issue. I'm concerned that the overall reference (H3) site numbering is also incorrect. I think the first number in H3 should refer to the first residue in the ectodomain, but right now it is a residue in the signal peptide.

@Bernadetadad, we should double check how all of these numbering schemes were generated. How was that done?

Also, is the H1 reference numbering scheme important? We can keep it if it is, but I just wasn't sure what this was used for (defer to your judgment).

**Comment by Bernadetadad** [comment]
I’m sure this is correct numbering is based of this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4229193/ and alignment was done by HA subtype conversion tool on BVRC. I think the signal peptide maybe looks a bit strange because signal peptides of H3 and H5 don’t really align. The screenshot shows alignment, highlighted A ia number 11 position in H3 if you number that back to the 1st position in H5 you end up having -6. The signal peptides don't align, show I have labeled that something else than negative numbers?
<img width="212" alt="image" src="https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/e0a88a3c-8913-4f6c-9d10-f4a77038e8f1">

**Comment by jbloom** [comment]
But if you look at Table 1 of the paper you linked above, that is not what it shows. The first residue in the ectodomain of H3 is the Q, not the A in the signal peptide. Are we sure that this is being aligned correctly by whatever tool you are using.

**Comment by jbloom** [comment]
I think the ectodomains should be aligned. I think here you have an extremely poor quality alignment that is making you align the beginning of the H3 ectodomain with a region halfway through the H5 signal peptide.

**Comment by Bernadetadad** [comment]
But the first aligning part (in the paper) in D of H5 and A of H3, the ectodomains don't start 1-1 they align 17-11 H5-H3. I guess the confusion is how to number the the preceding (1-10) sites in H3

**Comment by jbloom** [comment]
I am going to try aligning the two ectodomains and see what happens with that.

**Comment by jbloom** [comment]
Before I start that, what about the H1 reference site numbering? Do we want to keep that, and if so how was it generated so I can check that too.

**Comment by Bernadetadad** [comment]
A/United Kingdom/1/1933 for H1 and A/Aichi/2/1968 for H3

**Comment by Bernadetadad** [comment]
I've aligned with Clustal and it gives me the same alignment. Note the renumbering only used mature sequence.
<img width="1232" alt="image" src="https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/de92a170-17d2-4461-a5d1-25f743bbfc7f">

**Comment by jbloom** [comment]
OK, I now understand after your explanation re Figure 1 of [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4229193/). The signal peptide region may not be aligned quite right, but everything in the ectodomain is consitently numbered in the H3 comparison which I think is sufficient.
