### ISSUE TITLE
better main image for homepage

### ISSUE THREAD

**Issue by jbloom** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#86]
@Bernadetadad, the main image for the homepage (the one at right when looking [here](https://dms-vep.org/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/) currently does not look very good. I'm not sure if it is the right image choice or not, but more than that it has a white background which doesn't look good.

Can you and/or @WillHannon-MCB figure out how to make this look better, or just choose a new image as you prefer?

**Comment by Bernadetadad** [comment]
We can have transparent background (att.). Do we really want to keep the bullet points, they are good for library summary but could just go in the page text and the image. I also quite like surface structure like Brendan has on his page
![Untitled-1](https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/0319f8cc-34bc-45eb-8bd7-93b785c4efc0)
![Untitled-2](https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/403d0e28-9592-48ee-8879-c697bc4f69b0)
![Untitled-3](https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/3a7b8686-f7dd-4e33-b065-50fd82d46a57)

**Comment by WillHannon-MCB** [comment]
I was thinking the same thing. Once you pick an image I can style it; namely, adding some padding around the image and rounding the corners.

**Comment by Bernadetadad** [comment]
Ok, I like the cartoonish HA rendering most.  I might also like to have pseudovirus cartoon there, could we see how either of those look like on the site? (attached both with transparent background)
![Untitled-4](https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/bf787371-01cc-48c5-ae64-3e497ba156c6)

![Untitled-2](https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/22810662/6c6ff84b-09e1-4798-a1dd-9eb64d0940b5)

**Comment by jbloom** [comment]
OK, I will let you two figure out which one you want, @Bernadetadad @WillHannon-MCB. Any are OK with me.

**Comment by Bernadetadad** [comment]
We changed it already, I think what we have now looks good, no?

**Comment by Bernadetadad** [comment]
Can I close this issue?

**Comment by Bernadetadad** [comment]
Anyway, I'm happy with the current image I'm closing this issues

**Comment by jbloom** [comment]
I still don't think it looks good. The text in the figure is tiny and barely shows up as it's gray against a colored background. I think either the figure should be simplified or the text / figure made bigger.
