### ISSUE TITLE
Nextstrain trees with DMS data

### ISSUE THREAD

**Issue by jbloom** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#89]
@jordan-ort, I'm posting this issue to consolidate our discussions on Slack to one place that is easier to keep track of. Hopefully that is OK?

Anyway, the trees you made already look great, these are the ones at:
 - https://nextstrain.org/groups/moncla-lab/h5nx/h5-dms/all-clades
 - https://nextstrain.org/groups/moncla-lab/h5nx/h5-dms/clade-2344b

However, we wanted to ask about a few things (check boxes below):

- [x] Can we post links to these trees on the DMS homepage we have made (https://dms-vep.org/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS)? I assume this is likely OK, but just wanted to confirm first.
- [x] Can you update to use the latest (and should now be final) DMS data? See details below on these data.
- [x] Can you change the title of the pages to refer to *A/American Wigeon/South-Carolina/2021* rather than *A/turkey/Indiana/22-003707-003/2022 *. Right now you have changed this everywhere **except** the titles of the pages.
- [x] Whenever you are able to add cattle sequences that is great.

**Regarding adding the latest DMS data**:
We have further refined the pipeline and QC-ed the data. We think there are a few things we could do to streamline and simplify what is shown on Nextstrain:
 - We have updated the CSV file with the mutation effects on phenotypes. It should be virtually identical to before, but could you now draw from this file as it is the one we are updating? The CSV file is [here](https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/blob/main/results/summaries/all_sera_escape.csv)
 - We think we should drop down to just the phenotypes shown in that file, namely the ones listed below. Note that this drops or renames a few of the currently displayed phenotypes, which should clarify / simplify and still capture the relevant info:
   - *mouse sera escape relative to A/American Wigeon/South-Carolina/2021*: this is the *mouse sera escape* column in the updated CSV
   - *ferret sera escape relative to A/American Wigeon/South-Carolina/2021*: this is the *ferret sera escape* column in the updated CSV
   - *HA stability*: this is the *stability* column in the CSV file; note the name here should change from *pH stability* to *HA stability*
   - *increase in a2,6 sialic acid usage* this is the *SA26 usage increase* column

**Comment by jordan-ort** [comment]
@jbloom For the mouse/ferret sera escape and HA stability, do you still want to only include positive values? Just double checking since you now have the SA26 column subset to positives, but not the others. (And yes, definitely feel free to post the links to these trees on your DMS page!)

**Comment by jbloom** [comment]
@jordan-ort, I just discussed with @Bernadetadad, and we think we would like to have only positive values for escape, but positive and negative for stability. For escape, we think the word "escape" sort of implies positive, so you can floor all values to zero before adding. But for stability, keep both positive and negative.

We also thought it was better not to keep both the positive and overall values, as I think that i just too confusing for a common user. So to recape:
 - escape: floor values at zero before adding mutation effects
 - stability: keep positive and negative
 - 2,6 usage: the values already already floored at 0 in the CSV, so just use those.

**Comment by jbloom** [comment]
@jordan-ort, things mostly look great, and we are starting to use these trees to make paper figures. Just two last requests if you are able to do these:
- this is my error, but can you also show _cell entry_ as a phenotype. It should be in the CSV, I just forgot to make it as an option
- is it possible to also include a tree that shows all the cattle sequences (and closely related avian and human ones)?

**Comment by jordan-ort** [comment]
@jbloom I just pushed the new trees to our Nextstrain group page. I think that I addressed all of your comments, but let me know if I missed anything. There are now three trees:
[All H5Nx](https://nextstrain.org/groups/moncla-lab/h5nx/h5-dms/all-clades)
[Clade 2.3.4.4b](https://nextstrain.org/groups/moncla-lab/h5nx/h5-dms/clade-2344b) (with all mammalian strains, including cattle outbreak)
[USA-specific clade 2.3.4.4b](https://nextstrain.org/groups/moncla-lab/h5nx/h5-dms/usa-clade-2344b) (shows a subsample of the current USA outbreak and includes all cattle/cattle-related strains)

**Comment by jbloom** [comment]
Looks great, thanks so much @jordan-ort
