### ISSUE TITLE
issue with Altair text when using dark mode

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#90]
If dark mode is enabled the text is not showing up correctly. Seems to work fine when page is set to light mode. 

<img width="849" alt="Screenshot 2024-05-09 at 3 18 26 PM" src="https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/assets/89543163/ec2a3c50-a1dd-48f7-bca8-f2b0f1d294d9">

**Comment by Bernadetadad** [comment]
@WillHannon-MCB I think this was the actual issue I had originally and it had nothing to do with my laptop per se just the dark mode. Is there anything that could be done about this?

**Comment by jbloom** [comment]
Could we just get rid of the dark mode? Is there a way to just disable that option?

That seems like by far the easiest thing. The white mode is fine, and the dark mode seems like an extra flair we don't need if all it does is cause problems or require a complex fix.

**Comment by WillHannon-MCB** [comment]
I disabled 'dark mode' in the example homepage. Here's a[ link to the files changed](https://github.com/dms-vep/dms-vep-pipeline-3/pull/134/files) if you want to do the same here. It's a single line added to the site config (`.vitepress/config.mjs`).
