### ISSUE TITLE
altair plots empty for mobile

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#96]
None of the embedded Altair plots are viewable on mobile devices. Do you know why @WillHannon-MCB? At this point probably doesn't matter, but most traffic to the website will probably be mobile, in which case the site will feel a bit empty.

**Comment by jbloom** [comment]
They show up on my phone.

**Comment by Bernadetadad** [comment]
I was never able to see any altair plots on my iPhone :(

**Comment by WillHannon-MCB** [comment]
I'm pretty sure this is an `Altair` issue. None of the `Altair` plots are visible on my phone. It doesn't matter where/how we host them.

**Comment by jbloom** [comment]
I wonder if the difference is an iPhone (is that what most of you use) versus Android (what I use)?

Anyway, if no `altair` plots (eg, even ones on `altair` website documentation) show up on iPhones then maybe we should raise a GitHub issue there?

**Comment by jbloom** [comment]
I am going to close this issue as I am pretty sure it is a larger issue with `altair` rather than specific to this repo. @WillHannon-MCB, if you don't think that is correct feel free to re-open.
