### ISSUE TITLE
H3 antigenic site annotation

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#97]
@jbloom the H3 antigenic map is currently annotated based on [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6158429/) paper from Palese. I see in France's paper she uses annotations based on a [different](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4482133/) reference and looks slightly different (I guess mostly larger antigenic region D). Do you know if one or other would be better to use?

**Comment by jbloom** [comment]
I think the one you are using is fine.
